yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/group/', include('posts.urls')),
    path('', include('posts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)

yatube/templates/includes/author.html
{% block content %}
<div class="row">
    <div class="col-md-3 mb-3 mt-1">
        <div class="card">
            <div class="card-body">
                <div class="h2">
                    {{ author.first_name }}
                    {{ author.last_name }}
                </div>
                <div class="h3 text-muted">
                    @{{ author.username }}
                </div>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="h6 text-muted">
                        Подписчиков: {{ author.following.count }} <br>
                        Подписан: {{ author.follower.count }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="h6 text-muted">
                        {% url 'post' username=author.username post_id=post.pk as the_url %}
                        {% if current_path == the_url %}
                        Записей: {{ author.posts.count }}
                        {% else %}
                        Записей: {{ author.posts.count }}
                        {% endif %}

                    </div>
                </li>
            </ul>
        </div>
        <li class="list-group-item">
            {% if following %}
            <a class="btn btn-lg btn-light"
               href="{% url 'profile_unfollow' author.username %}" role="button">
                Отписаться
            </a>
            {% else %}
            <a class="btn btn-lg btn-primary"
               href="{% url 'profile_follow' author.username %}" role="button">
                Подписаться
            </a>
            {% endif %}
        </li> 
    </div>

    {% endblock %}

yatube/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form action = "{% url 'add_comment' username=post.author post_id=post.pk %}" method="post">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

{% for item in post.comments.all %}
<div class="media card mb-4">
  <div class="media-body card-body">
    <h5 class="mt-0">
      <a href="{% url 'profile' item.author.username %}"
         name="comment_{{ item.id }}">{{ item.author.username }}</a>
    </h5>
    <p>{{ item.text|linebreaksbr }}</p>
  </div>
</div>
{% endfor %} 

yatube/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>

  <p class="m-0 text-dark text-center ">Социальная сеть
    <span style="color:red">Ya</span><span style="color:gray">My</span>Game © {% now " Y" %},
    все права защищены.
  </p>
</footer>

yatube/templates/includes/menu.html
{% if user.is_authenticated %}
<div class="row">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
        Избранные авторы
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if love_game %}active{% endif %}" href="{% url 'group_posts' slug='love_game' %}">
        Ваш ТОП
      </a>
    </li>
  </ul>
</div>
{% endif %}

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span><span style="color:gray">My</span>Game</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    <a class="p-2 text-dark" href="{% url 'new_post' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
      </svg>
    </a>
    <a class="p-2 text-dark" href="{% url 'profile' username=user.username %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
      </svg>
      {{ user.username }}.
    </a>
    <a class="p-2 text-dark" href="{% url 'password_change' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-unlock" viewBox="0 0 16 16">
        <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2zM3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H3z"/>
    </svg>
    </a>
    <a class="p-2 text-dark" href="{% url 'logout' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
        <path d="M7.5 1v7h1V1h-1z"/>
        <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z"/>
    </svg>
    </a>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
    <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/includes/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link"
         href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">
        {{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link"
         href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %} 

yatube/templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <p class="card-text">
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {% url 'post' username=author.username post_id=post.pk as the_url %}
      {% if current_path == the_url %}
        {{ post.text|linebreaksbr }}
      {% else %}
        {{ post.text|linebreaksbr|truncatechars:455 }}
      {% endif %}
    </p>
    {% if post.group %}
      <a class="card-link muted" href="{% url 'group_posts' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <a class="btn btn-sm" href="{% url 'post' post.author.username post.id %}" role="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
            <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
        </svg>
        {% if post.comments.exists %}
          {{ post.comments.count }}
        {% endif %}
        </a>
        {% if user == post.author %}
          <a class="btn btn-sm" href="{% url 'edit_post' post.author.username post.id %}" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
            </svg>
          </a>
        {% endif %}

        {% if post.post_like.count != 0 %}
        <a class="btn btn-sm" href="{% url 'like_follow' post.author.username post.id %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
          </svg>
          {{ post.post_like.count }}
        </a>
        {% else %}
        <a class="btn btn-sm" href="{% url 'like_follow' post.author.username post.id %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M4 10.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7a.5.5 0 0 0-.5.5zm3-4C7 5.672 6.552 5 6 5s-1 .672-1 1.5S5.448 8 6 8s1-.672 1-1.5zm4 0c0-.828-.448-1.5-1-1.5s-1 .672-1 1.5S9.448 8 10 8s1-.672 1-1.5z"/>
          </svg>
          {{ post.post_like.count }}
        </a>
        {% endif %}


      </div>
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>